<a href="https://colab.research.google.com/github/va2305/Bias_vs_Variance_Visualization/blob/main/tensors_in_pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [3]:
import torch
print(torch.__version__)

2.9.0+cpu


In [4]:
import torch
if torch.cuda.is_available():
  print("GPU is available")
  print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
  print("GPU not avilable. Use CPU")

GPU not avilable. Use CPU


Creating **Tensor**

In [ ]:
#using empty
a = torch.empty(2,3)

In [ ]:
#Check type
type(a)

torch.Tensor

In [ ]:
#Using zeroes
torch.zeros(3,4)

tensor([[0., 0., 0., 0.],
        [0., 0., 0., 0.],
        [0., 0., 0., 0.]])

In [ ]:
#Using ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [ ]:
#using rand
torch.rand(2,3)

tensor([[0.5867, 0.5616, 0.8026],
        [0.8168, 0.0244, 0.2070]])

In [ ]:
#using manual seed
torch.manual_seed(100)
torch.rand(2,3)


tensor([[0.1117, 0.8158, 0.2626],
        [0.4839, 0.6765, 0.7539]])

In [ ]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])


tensor([[1, 2, 3],
        [4, 5, 6]])

In [ ]:
#other ways

#arange
print("using arange ->", torch.arange(0,10,2))

#using linspace
print("using linspace ->", torch.linspace(0,10,10))

#using eye
print("using eye ->", torch.eye(5))

#using full
print("using full ->", torch.full((3,3),5))
,

using arange -> tensor([0, 2, 4, 6, 8])
using linspace -> tensor([ 0.0000,  1.1111,  2.2222,  3.3333,  4.4444,  5.5556,  6.6667,  7.7778,
         8.8889, 10.0000])
using eye -> tensor([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])
using full -> tensor([[5, 5, 5],
        [5, 5, 5],
        [5, 5, 5]])


''

Tensor **Shapes**

In [ ]:
x = torch.tensor([[1,2,3],[4,5,6]])
x.shape

torch.Size([2, 3])

In [ ]:
torch.empty_like(x)

tensor([[ 425201762305, 1168231104514,  188978561296],
        [2731599200340,    4294967299,           103]])

In [ ]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [ ]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [ ]:
torch.rand_like(x, dtype=torch.float32)

tensor([[0.2627, 0.0428, 0.2080],
        [0.1180, 0.1217, 0.7356]])

Tensor **Data Types**

In [ ]:
#find data type
x.dtype

torch.int64

In [ ]:
#assign data type
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [ ]:
#using to
x.to(torch.float32)

tensor([[1., 2., 3.],
        [4., 5., 6.]])

**Mathematical Operations**

Scaler Operations

In [ ]:
#Addition
x+2

#Subtraction
x-2

#Multiplication
x*2

#Division
x/2

#int division
(x*100)//2

#mod
((x*100)//2)%2

#Power
x**2


tensor([[ 1,  4,  9],
        [16, 25, 36]])

Element wise **Operation**

In [ ]:
a = torch.rand(2,3)
b = torch.rand(2,3)

print(a)
print(b)

tensor([[0.4460, 0.1342, 0.4965],
        [0.9421, 0.5518, 0.5666]])
tensor([[0.9003, 0.0646, 0.4049],
        [0.0040, 0.7934, 0.6719]])


In [ ]:
#add
a + b

#sub
a - b

#multiply
a * b

#division
a / b

#power
a ** b

#mod
a % b




tensor([[0.4460, 0.0051, 0.0916],
        [0.0029, 0.5518, 0.5666]])

In [ ]:
c = torch.tensor([1,-2,3,-4])

#abs
torch.abs(c)

#negative
torch.neg(c)

d = torch.tensor([1.9,2.3,3.4,4.5])

#round
torch.round(d)

#ceil
torch.ceil(d)

#floor
torch.floor(d)

#clamp
torch.clamp(d, min= 2, max=3)



tensor([2.0000, 2.3000, 3.0000, 3.0000])

Reduction **Operation**

In [6]:
m = torch.rand(2,3)
n = torch.rand(2,3)

print(m)
print(n)

m.add(n)
m.relu_()

tensor([[0.2551, 0.6875, 0.7251],
        [0.6193, 0.5338, 0.1369]])
tensor([[0.1671, 0.6534, 0.8225],
        [0.0599, 0.9911, 0.6877]])


tensor([[0.2551, 0.6875, 0.7251],
        [0.6193, 0.5338, 0.1369]])

Copying **Tensor**

In [8]:
a = torch.rand(2,3)
a

tensor([[0.1155, 0.0157, 0.9930],
        [0.8401, 0.8367, 0.8393]])

In [9]:
b = a
b

tensor([[0.1155, 0.0157, 0.9930],
        [0.8401, 0.8367, 0.8393]])

In [11]:
a[0][0] =  0
a

tensor([[0.0000, 0.0157, 0.9930],
        [0.8401, 0.8367, 0.8393]])

In [12]:
b

tensor([[0.0000, 0.0157, 0.9930],
        [0.8401, 0.8367, 0.8393]])

In [14]:
id(a)

138523756880000

In [15]:
id(b)

138523756880000

In [18]:
b = a.clone()
b

tensor([[0.0000, 0.0157, 0.9930],
        [0.8401, 0.8367, 0.8393]])

In [20]:
a[0][0] = 10
a

tensor([[10.0000,  0.0157,  0.9930],
        [ 0.8401,  0.8367,  0.8393]])

In [21]:
b

tensor([[0.0000, 0.0157, 0.9930],
        [0.8401, 0.8367, 0.8393]])

In [22]:
id(a)

138523756880000

In [23]:
id(b)

138523755347744

Tesnsors Operation on **GPU**

In [24]:
torch.cuda.is_available()

True

In [27]:
device = torch.device('cuda')

#creating new tensor on GPU
torch.rand((2,3), device= device)

#moving exisiting tensor into GPU
a = torch.rand(2,3)
a

tensor([[0.4203, 0.0928, 0.5511],
        [0.2601, 0.2987, 0.0343]])

In [28]:
a.to(device)

tensor([[0.4203, 0.0928, 0.5511],
        [0.2601, 0.2987, 0.0343]], device='cuda:0')

In [2]:
b = a.to(device)
b

NameError: name 'a' is not defined

In [6]:
import torch
import time

#Define the sizes of matrices
size = 10000 #Large size for performance comparison

#Create random matrices on CPU
matrix_cpu1 = torch.rand(size,size)
matrix_cpu2 = torch.rand(size, size)

#Measure time on CPU
start_time= time.time()
result_cpu = torch.matmul(matrix_cpu1, matrix_cpu2)
cpu_time= time.time() - start_time

print(f"Time on CPU: {cpu_time:4f} seconds")

#Move matrices on GPU
matrix_gpu1 = matrix_cpu1.to('cuda')
matrix_gpu2 = matrix_cpu2.to('cuda')

#Measure time on GPU
start_time = time.time()
result_gpu = torch.matmul(matrix_gpu1, matrix_gpu2) #matrix multiplication on GPU
torch.cuda.synchronize() #Ensure all GPU operations
gpu_time= time.time() - start_time

print(f"Time on GPU: {gpu_time:4f} seconds")

#compare results
print("\nSpeedUp (CPU time/ GPU Time):", cpu_time/ gpu_time)



Time on CPU: 28.659761 seconds


AssertionError: Torch not compiled with CUDA enabled

In [10]:
a = torch.ones(4,4)
a

a.reshape(2,2,2,2)
a

#unsqueeze
#image size
c = torch.rand(226,226,3)

NumPy and **Torch**

In [11]:
import numpy as np

a = torch.tensor([1,2,3])
a

tensor([1, 2, 3])

In [13]:
b = a.numpy()
b

type(b)

numpy.ndarray

In [16]:
c = np.array([1,2,3])
c
torch.from_numpy(c)

tensor([1, 2, 3])